### ISSUE TITLE
Dockerize Python app

### ISSUE THREAD

**Issue by naXa777** [guiszk/server#2]
Let's add Dockerfile and docker-compose.yml to your project.
More information in the article -> https://www.clickittech.com/devops/dockerize-flask-python-application/
I'm going to follow it step by step. Please assign me to this task.

Read here to learn more about what is Docker and why it's used https://www.docker.com/why-docker/

**Comment by guiszk** [comment]
Sure, I'll assign you.

**Comment by naXa777** [comment]
PR https://github.com/guiszk/server/pull/3
